support IPv6

diff --git a/lnxrouter b/lnxrouter
--- a/lnxrouter
+++ b/lnxrouter
@@ -26,12 +26,14 @@ usage() {
     echo "                          Usually use with --dns-proxy"
     echo 
     echo "  -g <gateway>            Set gateway IPv4 address, netmask is /24 (default: 192.168.18.1)"
+    echo "  -6                      Enable IPv6"
+    echo "  --p6 <prefix>           Set IPv6 prefix (length 64) (default: fd00:1:1:1:: )"
     echo "  --dns-proxy <port>      Redirect incoming port 53 to DNS proxy port. DNS server is disabled"
     echo "  --no-serve-dns          Disable DNS server"
     echo "  --no-dnsmasq            Disable dnsmasq server completely (DHCP and DNS)"
     echo "  --log-dns               Show DNS server query log"
     echo "  --dhcp-dns <IP1[,IP2]>|no"
-    echo "                          Set DNS offered by DHCP, or no DNS offered (default: gateway as DNS)"
+    echo "                          Set IPv4 DNS offered by DHCP (default: gateway as DNS)"
     echo "  -d                      DNS server will take into account /etc/hosts"
     echo "  -e <hosts_file>         DNS server will take into account additional hosts file"
     echo 
@@ -87,6 +89,9 @@ if [[ "$1" == "" ]]; then
 fi
 
 GATEWAY=192.168.18.1
+PREFIX6=fd00:1:1:1::
+IID6=1
+IPV6=0
 ROUTE_ADDRS=
 DHCP_DNS=gateway
 dnsmasq_NO_DNS=0
@@ -162,6 +167,15 @@ while [[ -n "$1" ]]; do
         -g)
             shift
             GATEWAY="$1"
+            shift
+            ;;
+        -6)
+            shift
+            IPV6=1
+            ;;
+        --p6)
+            shift
+            PREFIX6="$1"
             shift
             ;;
         --mac)
@@ -568,10 +582,15 @@ nm_restore_manage() {
 
 #=========
 
-alias iptables="iptables -w"
 iptables_()
 {
-    iptables $@ -m comment --comment "lnxrouter-$$-$SUBNET_IFACE"
+    iptables -w $@ -m comment --comment "lnxrouter-$$-$SUBNET_IFACE"
+    return $?
+}
+ip6tables_()
+{
+    ip6tables -w $@ -m comment --comment "lnxrouter-$$-$SUBNET_IFACE"
+    return $?
 }
 
 start_nat() {
@@ -580,12 +599,22 @@ start_nat() {
     iptables_ -v -t nat -I POSTROUTING -s ${GATEWAY%.*}.0/24 ! -d ${GATEWAY%.*}.0/24 ! -o ${SUBNET_IFACE} -j MASQUERADE || die
     iptables_ -v -I FORWARD -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -j ACCEPT || die
     iptables_ -v -I FORWARD -o ${SUBNET_IFACE} -d ${GATEWAY%.*}.0/24 -j ACCEPT || die
+    if [[ $IPV6 -eq 1 ]]; then
+        ip6tables_ -v -t nat -I POSTROUTING -s ${PREFIX6}/64 ! -d ${PREFIX6}/64 ! -o ${SUBNET_IFACE} -j MASQUERADE || die
+        ip6tables_ -v -I FORWARD -i ${SUBNET_IFACE} -s ${PREFIX6}/64 -j ACCEPT || die
+        ip6tables_ -v -I FORWARD -o ${SUBNET_IFACE} -d ${PREFIX6}/64 -j ACCEPT || die
+    fi
 }
 stop_nat() {
     echo "iptables: stop NAT"
     iptables_ -t nat -D POSTROUTING -s ${GATEWAY%.*}.0/24 ! -d ${GATEWAY%.*}.0/24 ! -o ${SUBNET_IFACE} -j MASQUERADE
     iptables_ -D FORWARD -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -j ACCEPT
     iptables_ -D FORWARD -o ${SUBNET_IFACE} -d ${GATEWAY%.*}.0/24 -j ACCEPT
+    if [[ $IPV6 -eq 1 ]]; then
+        ip6tables_ -t nat -D POSTROUTING -s ${PREFIX6}/64 ! -d ${PREFIX6}/64 ! -o ${SUBNET_IFACE} -j MASQUERADE
+        ip6tables_ -D FORWARD -i ${SUBNET_IFACE} -s ${PREFIX6}/64 -j ACCEPT
+        ip6tables_ -D FORWARD -o ${SUBNET_IFACE} -d ${PREFIX6}/64 -j ACCEPT
+    fi
 }
 
 allow_dns_port() {
@@ -593,21 +622,35 @@ allow_dns_port() {
     echo "iptables: allow DNS port access"
     iptables_ -v -I INPUT -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -d ${GATEWAY} -p tcp -m tcp --dport 53 -j ACCEPT || die
     iptables_ -v -I INPUT -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -d ${GATEWAY} -p udp -m udp --dport 53 -j ACCEPT || die
+    if [[ $IPV6 -eq 1 ]]; then
+        ip6tables_ -v -I INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p tcp -m tcp --dport 53 -j ACCEPT || die
+        ip6tables_ -v -I INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p udp -m udp --dport 53 -j ACCEPT || die
+    fi
 }
 unallow_dns_port() {
     echo "iptables: stop allowing DNS"
     iptables_ -D INPUT -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -d ${GATEWAY} -p tcp -m tcp --dport 53 -j ACCEPT
     iptables_ -D INPUT -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -d ${GATEWAY}  -p udp -m udp --dport 53 -j ACCEPT
+    if [[ $IPV6 -eq 1 ]]; then
+        ip6tables_ -D INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p tcp -m tcp --dport 53 -j ACCEPT
+        ip6tables_ -D INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p udp -m udp --dport 53 -j ACCEPT
+    fi
 }
 
 start_dhcp() {
     echo 
     echo "iptables: allow DHCP port access"
     iptables_ -v -I INPUT -i ${SUBNET_IFACE} -p udp -m udp --dport 67 -j ACCEPT || die
+    if [[ $IPV6 -eq 1 ]]; then
+        ip6tables_ -v -I INPUT -i ${SUBNET_IFACE} -p udp -m udp --dport 547 -j ACCEPT || die
+    fi
 }
 stop_dhcp() {
     echo "iptables: stop dhcp"
     iptables_ -D INPUT -i ${SUBNET_IFACE} -p udp -m udp --dport 67 -j ACCEPT
+    if [[ $IPV6 -eq 1 ]]; then
+        ip6tables_ -D INPUT -i ${SUBNET_IFACE} -p udp -m udp --dport 547 -j ACCEPT
+    fi
 }
 
 redirect_dns() {
@@ -619,6 +662,15 @@ redirect_dns() {
     # redirect 53 to dns proxy
     iptables_ -v -t nat -I PREROUTING -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -d ${GATEWAY} -p tcp -m tcp --dport 53 -j REDIRECT --to-ports ${TP_DNS_PORT} || die
     iptables_ -v -t nat -I PREROUTING -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -d ${GATEWAY} -p udp -m udp --dport 53 -j REDIRECT --to-ports ${TP_DNS_PORT} || die
+    
+    if [[ $IPV6 -eq 1 ]]; then
+        # allow input to  dns proxy port
+        ip6tables_ -v -I INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p tcp -m tcp --dport ${TP_DNS_PORT} -j ACCEPT || die
+        ip6tables_ -v -I INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p udp -m udp --dport ${TP_DNS_PORT} -j ACCEPT || die
+        # redirect 53 to dns proxy
+        ip6tables_ -v -t nat -I PREROUTING -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p tcp -m tcp --dport 53 -j REDIRECT --to-ports ${TP_DNS_PORT} || die
+        ip6tables_ -v -t nat -I PREROUTING -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p udp -m udp --dport 53 -j REDIRECT --to-ports ${TP_DNS_PORT} || die  
+    fi
 }
 unredirect_dns() {
     echo "iptables: stop dns proxy "
@@ -627,6 +679,14 @@ unredirect_dns() {
 
     iptables_ -t nat -D PREROUTING -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -d ${GATEWAY} -p tcp -m tcp --dport 53 -j REDIRECT --to-ports ${TP_DNS_PORT}
     iptables_ -t nat -D PREROUTING -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -d ${GATEWAY} -p udp -m udp --dport 53 -j REDIRECT --to-ports ${TP_DNS_PORT}
+    
+    if [[ $IPV6 -eq 1 ]]; then
+        ip6tables_ -D INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p tcp -m tcp --dport ${TP_DNS_PORT} -j ACCEPT
+        ip6tables_ -D INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p udp -m udp --dport ${TP_DNS_PORT} -j ACCEPT
+
+        ip6tables_ -t nat -D PREROUTING -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p tcp -m tcp --dport 53 -j REDIRECT --to-ports ${TP_DNS_PORT}
+        ip6tables_ -t nat -D PREROUTING -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -p udp -m udp --dport 53 -j REDIRECT --to-ports ${TP_DNS_PORT}
+    fi
 }
 
 start_redsocks() {
@@ -640,6 +700,7 @@ start_redsocks() {
     iptables_ -t nat -A REDSOCKS-${SUBNET_IFACE} -d 172.16.0.0/12 -j RETURN || die
     iptables_ -t nat -A REDSOCKS-${SUBNET_IFACE} -d 192.168.0.0/16 -j RETURN || die
     iptables_ -t nat -A REDSOCKS-${SUBNET_IFACE} -d 224.0.0.0/4 -j RETURN || die
+    
     iptables_ -v -t nat -A REDSOCKS-${SUBNET_IFACE} -p tcp -j REDIRECT --to-ports ${TP_PORT} || die
     iptables_ -v -t nat -A REDSOCKS-${SUBNET_IFACE} -p udp -j REDIRECT --to-ports ${TP_PORT} || die
 
@@ -647,6 +708,24 @@ start_redsocks() {
 
     iptables_ -v -I INPUT -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -p tcp -m tcp --dport ${TP_PORT}  -j ACCEPT || die
     iptables_ -v -I INPUT -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -p udp -m udp --dport ${TP_PORT}  -j ACCEPT || die
+    
+    if [[ $IPV6 -eq 1 ]]; then
+        ip6tables_ -t nat -N REDSOCKS-${SUBNET_IFACE} || die
+        ip6tables_ -t nat -A REDSOCKS-${SUBNET_IFACE} -d fc00::/7 -j RETURN || die
+        ip6tables_ -t nat -A REDSOCKS-${SUBNET_IFACE} -d fe80::/10 -j RETURN || die
+        ip6tables_ -t nat -A REDSOCKS-${SUBNET_IFACE} -d ff00::/8 -j RETURN || die
+        ip6tables_ -t nat -A REDSOCKS-${SUBNET_IFACE} -d ::1 -j RETURN || die
+        ip6tables_ -t nat -A REDSOCKS-${SUBNET_IFACE} -d :: -j RETURN || die
+        ip6tables_ -t nat -A REDSOCKS-${SUBNET_IFACE} -d 0100::/64 -j RETURN || die
+
+        ip6tables_ -v -t nat -A REDSOCKS-${SUBNET_IFACE} -p tcp -j REDIRECT --to-ports ${TP_PORT} || die
+        ip6tables_ -v -t nat -A REDSOCKS-${SUBNET_IFACE} -p udp -j REDIRECT --to-ports ${TP_PORT} || die
+
+        ip6tables_ -v -t nat -I PREROUTING -i ${SUBNET_IFACE} -s ${PREFIX6}/64 -j REDSOCKS-${SUBNET_IFACE} || die
+
+        ip6tables_ -v -I INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64 -p tcp -m tcp --dport ${TP_PORT}  -j ACCEPT || die
+        ip6tables_ -v -I INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64 -p udp -m udp --dport ${TP_PORT}  -j ACCEPT || die   
+    fi
 }
 stop_redsocks() {
     echo "iptables: stop transparent proxy"
@@ -656,6 +735,15 @@ stop_redsocks() {
     
     iptables_ -D INPUT -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -p tcp -m tcp --dport ${TP_PORT}  -j ACCEPT
     iptables_ -D INPUT -i ${SUBNET_IFACE} -s ${GATEWAY%.*}.0/24 -p udp -m udp --dport ${TP_PORT}  -j ACCEPT
+    
+    if [[ $IPV6 -eq 1 ]]; then
+        ip6tables_ -t nat -D PREROUTING -i ${SUBNET_IFACE} -s ${PREFIX6}/64  -j REDSOCKS-${SUBNET_IFACE}
+        ip6tables_ -t nat -F REDSOCKS-${SUBNET_IFACE}
+        ip6tables_ -t nat -X REDSOCKS-${SUBNET_IFACE}
+        
+        ip6tables_ -D INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64 -p tcp -m tcp --dport ${TP_PORT}  -j ACCEPT
+        ip6tables_ -D INPUT -i ${SUBNET_IFACE} -s ${PREFIX6}/64 -p udp -m udp --dport ${TP_PORT}  -j ACCEPT
+    fi
 }
 
 kill_processes() {
@@ -931,6 +1019,10 @@ fi
 
 if [[ $SHARE_METHOD == 'none' ]]; then
     dnsmasq_NO_DNS=1
+fi
+
+if [[ $IPV6 -eq 1 ]]; then
+    GATEWAY6=${PREFIX6}${IID6}
 fi
 
 if [[ -d /dev/shm ]]; then
@@ -1268,6 +1360,7 @@ dhcp-range=${GATEWAY%.*}.10,${GATEWAY%.*}.250,255.255.255.0
 dhcp-option-force=option:router,${GATEWAY}
 #log-dhcp
 log-facility=/dev/null
+bogus-priv
 EOF
 # 'log-dhcp' show too much logs. Using '-d' in dnsmasq command shows a proper dhcp log
 # if use '-d', 'log-facility' should = /dev/null
@@ -1292,6 +1385,15 @@ EOF
     [[ -n "$ADDN_HOSTS" ]] && echo "addn-hosts=${ADDN_HOSTS}" >> $CONFDIR/dnsmasq.conf
     if [[ ! "$SHOW_DNS_QUERY" -eq 0 ]]; then
         echo log-queries=extra >> $CONFDIR/dnsmasq.conf
+    fi
+    if [[ $IPV6 -eq 1 ]];then
+        cat << EOF  >> $CONFDIR/dnsmasq.conf
+listen-address=${GATEWAY6}
+enable-ra
+#quiet-ra
+dhcp-range=interface:${SUBNET_IFACE},::1,::ffff:ffff:ffff:fffe,constructor:${SUBNET_IFACE},ra-only,64
+dhcp-option=option6:dns-server,[${GATEWAY6}]
+EOF
     fi
 fi
 
@@ -1341,6 +1443,9 @@ if [[ $WIFI_IFACE ]]; then
 fi
 
 ip addr add ${GATEWAY}/24 broadcast ${GATEWAY%.*}.255 dev ${SUBNET_IFACE} || die "Failed setting ${SUBNET_IFACE} IP"
+if [[ $IPV6 -eq 1 ]]; then
+    ip -6 addr add ${GATEWAY6}/64  dev ${SUBNET_IFACE} || die "Failed setting ${SUBNET_IFACE} IPv6"
+fi
 
 # enable Internet sharing
 if [[ "$SHARE_METHOD" == "none" ]]; then
